# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us James Wrong <983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-env-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
data:
{{- if not (empty .Values.envConfigs) }}
  {{- range $key, $value := .Values.envConfigs}}
  {{ $key }}: "{{ $value }}"
  {{- end}}
{{- else if not (empty .Values.global.envConfigs) }}
  {{- range $key, $value := .Values.global.envConfigs }}
  {{ $key }}: "{{ $value }}"
  {{- end}}
{{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-agent-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
data:
{{- if not (empty .Values.agentConfigs)}}
  {{- range $key, $value := .Values.agentConfigs}}
  {{ $key }}: "{{ $value }}"
  {{- end}}
{{- else if not (empty .Values.global.agentConfigs) }}
  {{- range $key, $value := .Values.global.agentConfigs}}
  {{ $key }}: "{{ $value }}"
  {{- end}}
{{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-app-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
data:
{{- if not (empty .Values.appConfigs)}}
  {{- range $key, $value := .Values.appConfigs}}
  {{ $key }}: "{{ $value }}"
  {{- end}}
{{- else if not (empty .Values.global.appConfigs) }}
  {{- range $key, $value := .Values.global.appConfigs}}
  {{ $key }}: "{{ $value }}"
  {{- end}}
{{- end}}
