# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

## see:https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}-upgrade
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}

spec:
  {{- if .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.replicaCount }}
  {{- else }}
  replicas: 2
  {{- end }}

  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "Recreate" }}
    rollingUpdate: null
    {{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.governance.type "Istio" }}
        ## Must match 'namespaceSelector' to take effect.
        ## see:https://preliminary.istio.io/latest/docs/ops/configuration/mesh/injection-concepts/
        sidecar.istio.io/inject: "true"
      {{- end }}
      labels:
        app.kubernetes.io/component: application
        app.kubernetes.io/name: {{ template "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        ## for canary governance labels.
        app.kubernetes.io/canaryVersion: {{ .Values.image.upgradeTag | default .Chart.AppVersion }}

    spec:
      {{- if .Values.initContainers }}
      initContainers:
      {{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}

      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      serviceAccountName: {{ template "app.name" . }}

      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}

      volumes:
      ## agent configuration.
      - name: agentconfig-volume
        configMap:
          name: {{ template "app.name" . }}-agent-configmap
          items:
          - key: agent.config
            path: agent.yaml
      ## spring application core configuration.
      ## see:https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-specific-path-in-the-volume
      - name: appconfig-volume
        configMap:
          name: {{ template "app.name" . }}-app-configmap
          items:
          {{- range $key, $value := .Values.appConfigs}}
          - key: {{$key}}.config
            path: {{$key}}
          {{- end}}
      ## data(transactions).
      - name: appdata-volume
      {{- if not .Values.persistence.enabled }}
        emptyDir: {}
      {{- else if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
        {{- with .Values.persistence.existingClaim }}
          claimName: {{ tpl . $ }}
        {{- end }}
      {{- end }}
      ## log.
      - name: applog-volume
        emptyDir: {}

      restartPolicy: Always

      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.upgradeTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: [ "/bin/sh", "-c", "env" ]
          ports:
            - name: http-api
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
            - name: http-management
              containerPort: {{ .Values.service.managementPort }}
              protocol: TCP

          ## see:https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
          #env:
          #- name: APP_NAME
          #  value: {{ .Release.Name }}
          #- name: JAVA_OPTS
          #  value: "-Djava.awt.headless=true"
          #- name: SERVER_PORT
          #  value: '8080'

          ## see:https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
          envFrom:
          - configMapRef:
              name: {{ template "app.name" . }}-env-configmap

          volumeMounts:
          ## sharding server and rules configuration.
          ## see:https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-specific-path-in-the-volume
          - name: appconfig-volume
            # e.g: /opt/apps/ecm/myapp-1.0.0-bin/conf
            #mountPath: /opt/apps/ecm/{{ template "app.name" . }}-package/{{ template "app.name" . }}-{{ .Chart.AppVersion }}-bin/conf/
            mountPath: /opt/apps/ecm/{{ template "app.name" . }}-package/{{ template "app.name" . }}-current/conf/
          ## datadir.
          - name: appdata-volume
            #mountPath: /opt/apps/ecm/{{ template "app.name" . }}-package/{{ template "app.name" . }}-{{ .Chart.AppVersion }}-bin/data/
            mountPath: /opt/apps/ecm/{{ template "app.name" . }}-package/{{ template "app.name" . }}-current/data/
          ## logdir.
          - name: applog-volume
            #mountPath: /opt/apps/ecm/{{ template "app.name" . }}-package/{{ template "app.name" . }}-{{ .Chart.AppVersion }}-bin/log/
            mountPath: /opt/apps/ecm/{{ template "app.name" . }}-package/{{ template "app.name" . }}-current/log/

          ## see:https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
            # tcpSocket:
            #   port: http-api
            httpGet:
              scheme: HTTP
              httpHeaders:
              - name: Accept
                value: "application/json"
              path: /actuator/health
              port: http-management

          ## see:https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: http-management

          ## see:https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 2
            successThreshold: 1
            httpGet:
              scheme: HTTP
              httpHeaders:
              - name: Accept
                value: "application/json"
              path: /actuator/health
              port: http-management

          {{- if .Values.resources.enabled }}
          resources:
            requests: {{- toYaml .Values.resources.requests | nindent 14 }}
            limits: {{- toYaml .Values.resources.limits | nindent 14 }}
          {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
