# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment base configuration. ####
#

# #### Spring boot configuration. ####
#
spring:
  application.name: iam-web
  profiles:
    include: common,util,default
    active: dev
  banner:
    location: classpath:META-INF/banner.txt
  ## see:https://reflectoring.io/spring-boot-tracing/
  ## The entry of bind attrs to reactor context see:org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth#runMonoSupplierInScope()
  sleuth:
    enabled: true
    ## see:org.springframework.cloud.sleuth.autoconfig.instrument.web.TraceWebFluxConfiguration
    ## see:org.springframework.cloud.sleuth.autoconfig.instrument.web.SleuthWebProperties
    web:
      ## [Note]: In order to use canary tracking instead of the original TraceWebFilter, that must be turned off.
      ## see:com.wl4g.iam.gateway.trace.config.GrayTraceAutoConfiguration#canaryTraceWebFilter()
      enabled: false
      #skipPattern:
      #filterOrder:
      #ignoreAutoConfiguredSkipPatterns: false
    ### see:org.springframework.cloud.sleuth.autoconfig.brave.SleuthProperties
    #traceId128: false
    #supportsJoin: false
    ### see:org.springframework.cloud.sleuth.autoconfig.SleuthOpentracingProperties
    #opentracing:
    #  enabled: true
    ### see:org.springframework.cloud.sleuth.autoconfig.brave.ConditionalOnBraveEnabled
    ### see:org.springframework.cloud.sleuth.autoconfig.SleuthTracerProperties
    #tracer:
    #  mode: AUTO
    ### see:org.springframework.cloud.sleuth.autoconfig.brave.SamplerProperties
    #sampler:
    #  probability: 
    #  rate: 10
    ### see:org.springframework.cloud.sleuth.autoconfig.brave.instrument.grpc.BraveGrpcAutoConfiguration
    #grpc:
    #  enabled: true
    #zipkin:
    #  #sender: WEB ## Default by null, options(WEB|KAFKA|...)
    ## see:org.springframework.cloud.sleuth.autoconfig.otel.SleuthPropagationProperties
    propagation:
      type: [B3,AWS,JAEGER,OT_TRACER,W3C] ## Default by B3, options(B3|AWS|JAEGER|W3C|OT_TRACER|CUSTOM)
      tag.enabled: true
    ## see:org.springframework.cloud.sleuth.autoconfig.SleuthBaggageProperties
    ## see:https://docs.spring.io/spring-cloud-sleuth/docs/3.1.1/reference/htmlsingle/#features-baggage
    baggage:
      ## Enables correlating the baggage context with logging contexts.
      correlationEnabled: true
      ## List of fields that should be propagated over the wire.
      correlationFields: principal
      ## List of fields that should automatically become tags.
      tagFields:
        - x-request-id
        - principal
        - region-code
      ## List of fields that should be accessible within the JVM process but not propagated over the wire.
      localFields:
        - x-request-id
        - principal
        - region-code
      ## List of fields that are referenced the same in-process as it is on the wire. For example, the field "x-vcap-request-id" would be set as-is including the prefix.
      remoteFields:
        - x-request-id
        - principal
        - region-code
    otel:
      ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelProperties
      config:
        ## Instrumentation name to be used to find a Tracer.
        instrumentationName: "org.springframework.cloud.spring-cloud-sleuth"
        ## Instrumentation version to be used to find a Tracer.
        #instrumentationVersion
        ## Sets the global default {@code Sampler} value.
        traceIdRatioBased: 1d ## Default by 0.1
        ## Returns the global default max number of attributes per {@link Span}.
        maxAttrs: 128 ## Default by 128
        ## Returns the global default max number of events per {@link Span}.
        maxEvents: 128 ## Default by 128
        ## Returns the global default max number of link entries per {@link Span}.
        maxLinks: 128 ## Default by 128
        ## Returns the global default max number of attributes per event.
        maxEventAttrs: 128 ## Default by 128
        ## Returns the global default max number of attributes per link.
        maxLinkAttrs: 128 ## Default by 128
      resource:
        enabled: true
      ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelPropagationProperties
      ## see:org.springframework.cloud.sleuth.otel.propagation.CompositeTextMapPropagator
      propagation:
        ## see:Enables default B3 Sleuth Baggage propagation. This will be automatically turned on when B3 propagation type gets picked.
        sleuthBaggage.enabled: true
        ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelPropagationConfiguration.PropagatorsConfiguration
        compositeTextMapPropagator.enabled: true
      ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelLogConfiguration
      ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelLogProperties
      ## The scope fields into MDC see:org.springframework.cloud.sleuth.otel.bridge.Slf4jBaggageApplicationListener#onScopeAttached()
      log:
        exporter.enabled: true ## Default by false
        slf4j.enabled: true ## Default by false
      ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelProcessorProperties
      processor:
        batch:
          ## The interval, in milliseconds, between two consecutive exports. Default is 5000.
          scheduleDelay: 5000
          ## The maximum queue size. Default is 2048.
          maxQueueSize: 2048
          ## The maximum batch size. Default is 512.
          maxExportBatchSize: 512
          ## The maximum allowed time, in milliseconds, to export data. Default is 30000.
          exporterTimeout: 30000
      ## see:org.springframework.cloud.sleuth.autoconfig.otel.OtelExporterProperties
      exporter:
        sleuthSpanFilter.enabled: true
        #otlp:
        #  endpoint: http://localhost:4317
        #  timeout: 10000
        jaeger:
          endpoint: http://localhost:14250
          timeout: 10000

# Logging configuration.
logging:
  file:
    # see:com.wl4g.infra.core.logging.logback.EnhancedLogbackConfigurer#apply
    # see:org.springframework.boot.logging.LogFile#toString
    name: ${server.tomcat.basedir}/../log/${spring.application.name}/${spring.application.name}.log
    clean-history-on-start: false # By default: false
    total-size-cap: 200GB # By default: 200GB
    max-size: 1GB # By default: 500MB
    max-history: 30 # By default: 7
  pattern:
    #console: ${logging.pattern.file.name}
    #file: '%d{yy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%4p} ${PID} [%t] [%X{_H_:X-Request-ID}] [%X{_H_:X-Request-Seq}] [%X{_C_:${spring.iam.cookie.name}}] - %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    #dateformat: yyyy-MM-dd HH:mm:ss.SSS
    #level: '%5p'
    #rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  root: INFO
  level:
    de.codecentric.boot.admin: INFO
    org:
      springframework: INFO
        #boot.context.config: DEBUG # Print load config
      apache: INFO
    feign: DEBUG
    com:
      wl4g.iam.web: DEBUG

# ### Server configuration. ###
server: ## see:org.springframework.boot.autoconfigure.web.ServerProperties
  port: 18080
  address: 0.0.0.0
  servlet:
    contextPath: /${spring.application.name}
  tomcat: # see: org.springframework.boot.autoconfigure.web.ServerProperties.Tomcat
    basedir: /tmp/${spring.application.name}
    accesslog:
      enabled: false
      directory: ${server.tomcat.basedir}/../log/${spring.application.name}/ # Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
      requestAttributesEnabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
    backgroundProcessorDelay: 1000 # default: 10s
    thread:
      # Maximum amount of worker threads. for example 4C 8G, and the empirical value of thread number is 800. The operating system 
      # has system overhead for switching and scheduling between threads, so not the more the better. The minimum number of idle working threads
      # is 10 by default. (increase it appropriately to cope with the sudden increase of visits). default: 200
      max: 50
      min-spare: 5 # Minimum amount of worker threads. default: 10
    # Maximum number of connections that the server accepts and processes at any given time. Once the limit has been reached, the
    # operating system may still accept connections based on the "acceptCount" property. default: 8192
    maxConnections: 8192
    # Maximum queue length for incoming connection requests when all possible request processing threads are in use. defualt: 100
    accept-count: 100
    # Maximum number of idle processors that will be retained in the cache and reused with a subsequent request. When set to -1 
    # the cache will be unlimited with a theoretical maximum size equal to the maximum number of connections. default: 200
    processorCache: 200
    maxHttpFormPostSize: 2MB # Maximum size of the form content in any HTTP post request.
    maxSwallowSize: 2MB # Maximum amount of request body to swallow.
    uri-encoding: UTF-8
    mbeanregistry:
      enable: true
    remoteip:
      remoteIpHeader: X-Forwarded-For
      protocolHeader: X-Forwarded-Proto
      hostHeader: X-Forwarded-Host
      portHeader: X-Forwarded-Port
