# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @see: https://helm.sh/zh/docs/topics/charts/
#
apiVersion: v2
name: iam-web
description: A Helm chart for IAM WEB
icon: https://raw.githubusercontent.com/wl4g/iam/master/shots/iam-logo.png?token=GHSAT0AAAAAABWBQKN3QNYHECQ5LR4PCLKMYWGQIGA
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.0.0

# Onwer maintainers.
maintainers:
  - name: James Wong
    email: wanglsir@gmail.com
    url: https://github.com/wl4g

# For best performance, these stateful storage services, which are relied upon below, usually use services
# outside the kubernetes cluster (headless endpoints) in production environments.
dependencies:
  - name: bitnami/redis-cluster
    condition: redis.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "7.6.4"
  - name: bitnami/kafka
    condition: kafka.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "18.0.0"
  # - name: flink
  #   repository: "file://../flink-charts"
  #   version: "0.1.0"
  # - name: hbase
  #   repository: "file://../hbase-charts"
  #   version: "0.1.0"