apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-env-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
data:
  ## NOTES: Environment variable values must use double or single quotes.
  ## see:https://stackoverflow.com/questions/59354115/helm-upgrade-fails-with-error-expects-or-n-but-found-t
  SPRING_APPLICATION_NAME: {{ .Release.Name }}
{{- range $key, $value := .Values.envConfigs}}
  {{ $key }}: {{ $value }}
{{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-agent-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
data:
  agent.config: {{ toYaml .Values.agentConfig | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-app-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
data:
{{- range $key, $value := .Values.appConfigs}}
  {{ $key }}.config: {{ toYaml $value | indent 2 }}
{{- end}}
